<a href="https://colab.research.google.com/github/gabrielcdo/Pytorch/blob/main/yolov5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/ultralytics/yolov5.git

Cloning into 'yolov5'...
remote: Enumerating objects: 9043, done.
remote: Total 9043 (delta 0), reused 0 (delta 0), pack-reused 9043
Receiving objects: 100% (9043/9043), 9.71 MiB | 13.15 MiB/s, done.
Resolving deltas: 100% (6272/6272), done.


In [ ]:
!pip3 install -r /content/yolov5/requirements.txt

In [ ]:
import torch
import cv2
from google.colab.patches import cv2_imshow
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
#model = torch.hub.load('ultralytics/yolov5', 'custom', path='best.pt')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

Using cache found in /root/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-9-20 torch 1.9.0+cu102 CUDA:0 (Tesla K80, 11441.1875MB)

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding AutoShape... 


cuda


In [ ]:

color = (255, 0, 0)
cap  = cv2.VideoCapture('/content/drive/MyDrive/13.mp4')

class_names = []
with open("coco.names", "r") as f:
    class_names = [cname.strip() for cname in f.readlines()]

In [ ]:
while True:
    _,img = cap.read()
    res = model(img)
    rets = []
    for i in res.xyxy[0]:
        print(str(i) + class_names[int(i[5])])
        x1 = int(i[0])
        y1= int(i[1])
        x2 = int(i[2])
        y2 = int(i[3])
        rets.append([[x1,y1,x2,y2], class_names[int(i[5])]])

    for ret,nomes in rets:
        #print(ret[0])
        start = [ret[0],ret[1]]
        end = [ret[2],ret[3]]
        img = cv2.rectangle(img,(start[0], start[1] , end[0], end[1]) ,color,2)
        cv2.putText(img, nomes, (ret[0], ret[1] - 2), 1 , 2 ,(255,255,255), thickness=1,lineType=cv2.LINE_AA)
    #cv2_imshow(img)
    #if cv2.waitKey(1) == 27:
    #    break
cap.release()
cv2.destroyAllWindows()

tensor([5.24250e+02, 5.62500e-01, 8.80500e+02, 3.42188e+02, 8.70605e-01, 2.00000e+00], device='cuda:0')car
tensor([1.58850e+03, 3.28125e+01, 1.68750e+03, 3.63000e+02, 7.75879e-01, 0.00000e+00], device='cuda:0')person
tensor([1.72350e+03, 1.87500e-01, 1.91850e+03, 2.32312e+02, 2.79785e-01, 7.00000e+00], device='cuda:0')truck
tensor([5.25375e+02, 2.62500e+00, 8.90250e+02, 3.61500e+02, 8.33008e-01, 2.00000e+00], device='cuda:0')car
tensor([1.59000e+03, 3.86250e+01, 1.69200e+03, 3.61875e+02, 7.86133e-01, 0.00000e+00], device='cuda:0')person
tensor([5.30250e+02, 1.20000e+01, 9.11250e+02, 3.87750e+02, 8.08105e-01, 2.00000e+00], device='cuda:0')car
tensor([1.59000e+03, 3.82500e+01, 1.69500e+03, 3.64125e+02, 7.55371e-01, 0.00000e+00], device='cuda:0')person
tensor([1.59000e+03, 3.78750e+01, 1.69500e+03, 3.64125e+02, 7.88086e-01, 0.00000e+00], device='cuda:0')person
tensor([5.33250e+02, 2.49375e+01, 9.23250e+02, 4.06500e+02, 7.18750e-01, 2.00000e+00], device='cuda:0')car
tensor([1.69050e+03, 0.

AttributeError: ignored